### PR TITLE
Fix `PermissionDenied` for `listAssessmentResults` in case of `AuthorizationStrategyAllowAll`

### LINKED ISSUE #873: ListAssessmentResult fails with filtered_cloud_service_id
**Describe the bug**
ListAssessmentResult does not filter by the Cloud Service ID.

Without filtered_cloud_service_id everything works
`grpcurl --plaintext -H "authorization: Bearer $TOKEN" localhost:9090 clouditor.Orchestrator.ListAssessmentResult`  assessmentResults

With filtered_cloud_service_id a PermissionDenied error returns
```
grpcurl --plaintext -d '{"filtered_cloud_service_id":"00000000-0000-0000-0000-000000000000"}' -H "authorization: Bearer $TOKEN" localhost:9090 clouditor.Orchestrator.ListAssessmentResults
ERROR:
  Code: PermissionDenied
  Message: access denied
```

### PR DESCRIPTION
**Pull request by lebogg**
Fixes #873.
In  `all, allowed = svc.authz.AllowedCloudServices(ctx)`, `all` is true and the list`allowed` nil if the strategy is `AuthorizationStrategyAllowAll`. And if `all` is true, the list shouldn't be checked. I adjusted the if condition accordingly and changed a bit the comments of `AuthorizationStrategyAllowAll` interface methods.

### CODE REVIEW

File: service/orchestrator/assessment_results.go [hunk 1]
```diff
@@ -47,8 +48,8 @@ func (svc *Service) ListAssessmentResults(ctx context.Context, req *assessment.L
 	// only allowed, if one can access all the cloud services. Furthermore, the content of the filtered cloud service ID
 	// must be in the list of allowed cloud service IDs.
 	all, allowed = svc.authz.AllowedCloudServices(ctx)
-	if (req.FilteredCloudServiceId == "" && !all) ||
-		(req.FilteredCloudServiceId != "" && !slices.Contains(allowed, req.FilteredCloudServiceId)) {
+	if !all && (req.FilteredCloudServiceId == "" ||
```
Comment (oxisto) [inline service/orchestrator/assessment_results.go:51]: Should be solid now. Could we actually add more tests to this since we obviously did not catch this mistake with our current tests?

**Review by oxisto — APPROVED** [review]
